name = "ipl-worker"
main = "src/index.ts"
compatibility_date = "2023-10-16"
node_compat = true
vars = { ENVIRONMENT = "development" }

# Local development
kv_namespaces = [
 { binding = "CONTENT_KV", id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
]
r2_buckets = [
 { binding = "CLIENT_CONTENT", bucket_name = "ipl-content" }
]

# Production
[env.production]
 vars = { ENVIRONMENT = "production", SHARD_NAME = "MyShard" }
 kv_namespaces = [
  { binding = "CONTENT_KV", id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
 ]
 r2_buckets = [
  { binding = "CLIENT_CONTENT", bucket_name = "ipl-content" }
 ]

# Remote development
[env.development]
 vars = { ENVIRONMENT = "development", SHARD_NAME = "MyShard" }
 kv_namespaces = [
  { binding = "CONTENT_KV", id = "20cc82d316104590a4effd95058d7d1f" }
 ]
 r2_buckets = [
  { binding = "CLIENT_CONTENT", bucket_name = "ipl-content" }
 ]
